version: "2"
services:
  web:
    image: nginx
    ports:
      - "8080:81"
    volumes:
      - ./public:/code
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - code-network
  mysql:
    image: mysql
    volumes:
      - /data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: 123456
      MYSQL_ROOT_PASSWORD: 123456
    networks:
      - code-network
  php:
    image: php:7.0.12-fpm
    volumes:
      - ./code:/code
    networks:
      - code-network

networks:
  code-network:
    driver: bridge
